//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabster.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cabster.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonParticipantSortEnter {
            get {
                object obj = ResourceManager.GetObject("buttonParticipantSortEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonParticipantAddLeave {
            get {
                object obj = ResourceManager.GetObject("buttonParticipantAddLeave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonParticipantAddEnter {
            get {
                object obj = ResourceManager.GetObject("buttonParticipantAddEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonResizeLeave {
            get {
                object obj = ResourceManager.GetObject("buttonResizeLeave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonResizeEnter {
            get {
                object obj = ResourceManager.GetObject("buttonResizeEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonParticipantSortLeave {
            get {
                object obj = ResourceManager.GetObject("buttonParticipantSortLeave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonMinimizeLeave {
            get {
                object obj = ResourceManager.GetObject("buttonMinimizeLeave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FormHeaderSapiensia {
            get {
                object obj = ResourceManager.GetObject("FormHeaderSapiensia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon IconSapiensia {
            get {
                object obj = ResourceManager.GetObject("IconSapiensia", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FormBackground {
            get {
                object obj = ResourceManager.GetObject("FormBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonMinimizeEnter {
            get {
                object obj = ResourceManager.GetObject("buttonMinimizeEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonCloseLeave {
            get {
                object obj = ResourceManager.GetObject("buttonCloseLeave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonCloseEnter {
            get {
                object obj = ResourceManager.GetObject("buttonCloseEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize window..
        /// </summary>
        public static string Action_MinimizeWindow {
            get {
                return ResourceManager.GetString("Action.MinimizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize window..
        /// </summary>
        public static string Action_ResizeWindow {
            get {
                return ResourceManager.GetString("Action.ResizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close application..
        /// </summary>
        public static string Action_TerminateApplication {
            get {
                return ResourceManager.GetString("Action.TerminateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single operation was expected for: {Operation}.
        /// </summary>
        public static string Exception_Common_ExpectedSingleOperation {
            get {
                return ResourceManager.GetString("Exception.Common.ExpectedSingleOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was already a defined value or instance for {Property}..
        /// </summary>
        public static string Exception_Common_IsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("Exception.Common.IsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value or instance defined for {Property}..
        /// </summary>
        public static string Exception_Common_IsNullOrEmpty {
            get {
                return ResourceManager.GetString("Exception.Common.IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! I thought that this error would never occur..
        /// </summary>
        public static string Exception_Common_ThisWillNeverOccur {
            get {
                return ResourceManager.GetString("Exception.Common.ThisWillNeverOccur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the operation {Class}.{Method} one or more arguments are not valid: {Argument}.
        /// </summary>
        public static string Exception_Common_WrongArgument {
            get {
                return ResourceManager.GetString("Exception.Common.WrongArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {Configuration} configuration is managed externally and does not support some operations by the business application..
        /// </summary>
        public static string Exception_Infrastructure_ConfigurationIsManagedExternally {
            get {
                return ResourceManager.GetString("Exception.Infrastructure.ConfigurationIsManagedExternally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {Configuration} configuration is managed internally and does not support some operations by the scope outside the business application..
        /// </summary>
        public static string Exception_Infrastructure_ConfigurationIsManagedInternally {
            get {
                return ResourceManager.GetString("Exception.Infrastructure.ConfigurationIsManagedInternally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabster.
        /// </summary>
        public static string Name_System {
            get {
                return ResourceManager.GetString("Name.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Text_Common_Active {
            get {
                return ResourceManager.GetString("Text.Common.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Text_Common_Inactive {
            get {
                return ResourceManager.GetString("Text.Common.Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Text_DialogShow_ButtonCancel {
            get {
                return ResourceManager.GetString("Text.DialogShow.ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Text_DialogShow_ButtonClose {
            get {
                return ResourceManager.GetString("Text.DialogShow.ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Text_DialogShow_ButtonConfirm {
            get {
                return ResourceManager.GetString("Text.DialogShow.ButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interval starts after how many rounds.
        /// </summary>
        public static string Text_WorkGroup_BreakStartsAfterHowManyRounds_Part1 {
            get {
                return ResourceManager.GetString("Text.WorkGroup.BreakStartsAfterHowManyRounds_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rounds. Every {minutes} minute(s)..
        /// </summary>
        public static string Text_WorkGroup_BreakStartsAfterHowManyRounds_Part2 {
            get {
                return ResourceManager.GetString("Text.WorkGroup.BreakStartsAfterHowManyRounds_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of each break.
        /// </summary>
        public static string Text_WorkGroup_DurationOfEachBreak_Part1 {
            get {
                return ResourceManager.GetString("Text.WorkGroup.DurationOfEachBreak_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s)..
        /// </summary>
        public static string Text_WorkGroup_DurationOfEachBreak_Part2 {
            get {
                return ResourceManager.GetString("Text.WorkGroup.DurationOfEachBreak_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of each round.
        /// </summary>
        public static string Text_WorkGroup_DurationOfEachRound_Part1 {
            get {
                return ResourceManager.GetString("Text.WorkGroup.DurationOfEachRound_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s)..
        /// </summary>
        public static string Text_WorkGroup_DurationOfEachRound_Part2 {
            get {
                return ResourceManager.GetString("Text.WorkGroup.DurationOfEachRound_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the participant&apos;s name..
        /// </summary>
        public static string Text_WorkGroup_ParticipantAdd {
            get {
                return ResourceManager.GetString("Text.WorkGroup.ParticipantAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add a participant..
        /// </summary>
        public static string Text_WorkGroup_ParticipantAddHint {
            get {
                return ResourceManager.GetString("Text.WorkGroup.ParticipantAddHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a participant enter a name..
        /// </summary>
        public static string Text_WorkGroup_ParticipantNameEmpty {
            get {
                return ResourceManager.GetString("Text.WorkGroup.ParticipantNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant: {Participant}
        ///
        ///To activate or deactivate: right button.
        ///To remove: left button..
        /// </summary>
        public static string Text_WorkGroup_ParticipantRemoveHint {
            get {
                return ResourceManager.GetString("Text.WorkGroup.ParticipantRemoveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly sort the participants..
        /// </summary>
        public static string Text_WorkGroup_ParticipantSortHint {
            get {
                return ResourceManager.GetString("Text.WorkGroup.ParticipantSortHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Mob.
        /// </summary>
        public static string Text_WorkGroup_Start {
            get {
                return ResourceManager.GetString("Text.WorkGroup.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading another tip ....
        /// </summary>
        public static string Text_WorkGroup_TipsLoading {
            get {
                return ResourceManager.GetString("Text.WorkGroup.TipsLoading", resourceCulture);
            }
        }
    }
}
