//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabster.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cabster.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonCloseEnter {
            get {
                object obj = ResourceManager.GetObject("buttonCloseEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonCloseLeave {
            get {
                object obj = ResourceManager.GetObject("buttonCloseLeave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonConfigurationEnter {
            get {
                object obj = ResourceManager.GetObject("buttonConfigurationEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonConfigurationLeave {
            get {
                object obj = ResourceManager.GetObject("buttonConfigurationLeave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonLanguageEnglishEnter {
            get {
                object obj = ResourceManager.GetObject("buttonLanguageEnglishEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonLanguageEnglishLeave {
            get {
                object obj = ResourceManager.GetObject("buttonLanguageEnglishLeave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonLanguagePortugueseEnter {
            get {
                object obj = ResourceManager.GetObject("buttonLanguagePortugueseEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonLanguagePortugueseLeave {
            get {
                object obj = ResourceManager.GetObject("buttonLanguagePortugueseLeave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonMinimizeEnter {
            get {
                object obj = ResourceManager.GetObject("buttonMinimizeEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonMinimizeLeave {
            get {
                object obj = ResourceManager.GetObject("buttonMinimizeLeave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonNotificationEnter {
            get {
                object obj = ResourceManager.GetObject("buttonNotificationEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonNotificationLeave {
            get {
                object obj = ResourceManager.GetObject("buttonNotificationLeave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonParticipantAddEnter {
            get {
                object obj = ResourceManager.GetObject("buttonParticipantAddEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonParticipantAddLeave {
            get {
                object obj = ResourceManager.GetObject("buttonParticipantAddLeave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonParticipantSortEnter {
            get {
                object obj = ResourceManager.GetObject("buttonParticipantSortEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonParticipantSortLeave {
            get {
                object obj = ResourceManager.GetObject("buttonParticipantSortLeave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonResizeEnter {
            get {
                object obj = ResourceManager.GetObject("buttonResizeEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buttonResizeLeave {
            get {
                object obj = ResourceManager.GetObject("buttonResizeLeave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FormLockScreenBackground {
            get {
                object obj = ResourceManager.GetObject("FormLockScreenBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FormLayoutBackground {
            get {
                object obj = ResourceManager.GetObject("FormLayoutBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FormHeaderSapiensia {
            get {
                object obj = ResourceManager.GetObject("FormHeaderSapiensia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconParticipantDriver {
            get {
                object obj = ResourceManager.GetObject("iconParticipantDriver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon IconSapiensia {
            get {
                object obj = ResourceManager.GetObject("IconSapiensia", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconParticipantNavigator {
            get {
                object obj = ResourceManager.GetObject("iconParticipantNavigator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {Shortcut} shortcut key is already being used by another application..
        /// </summary>
        public static string Exception_Application_ShortcutAlreadyUsed {
            get {
                return ResourceManager.GetString("Exception.Application.ShortcutAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A single operation was expected for: {Operation}.
        /// </summary>
        public static string Exception_Common_ExpectedSingleOperation {
            get {
                return ResourceManager.GetString("Exception.Common.ExpectedSingleOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was already a defined value or instance for {Property}..
        /// </summary>
        public static string Exception_Common_IsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("Exception.Common.IsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value or instance defined for {Property}..
        /// </summary>
        public static string Exception_Common_IsNullOrEmpty {
            get {
                return ResourceManager.GetString("Exception.Common.IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! I thought that this error would never occur..
        /// </summary>
        public static string Exception_Common_ThisWillNeverOccur {
            get {
                return ResourceManager.GetString("Exception.Common.ThisWillNeverOccur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the operation {Class}.{Method} one or more arguments are not valid: {Argument}.
        /// </summary>
        public static string Exception_Common_WrongArgument {
            get {
                return ResourceManager.GetString("Exception.Common.WrongArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {Configuration} configuration is managed externally and does not support some operations by the business application..
        /// </summary>
        public static string Exception_Infrastructure_ConfigurationIsManagedExternally {
            get {
                return ResourceManager.GetString("Exception.Infrastructure.ConfigurationIsManagedExternally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {Configuration} configuration is managed internally and does not support some operations by the scope outside the business application..
        /// </summary>
        public static string Exception_Infrastructure_ConfigurationIsManagedInternally {
            get {
                return ResourceManager.GetString("Exception.Infrastructure.ConfigurationIsManagedInternally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabster.
        /// </summary>
        public static string Name_Application {
            get {
                return ResourceManager.GetString("Name.Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American English.
        /// </summary>
        public static string Name_Language_English {
            get {
                return ResourceManager.GetString("Name.Language.English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português Brasileiro.
        /// </summary>
        public static string Name_Language_Portuguese {
            get {
                return ResourceManager.GetString("Name.Language.Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Name_Term_Active {
            get {
                return ResourceManager.GetString("Name.Term.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Name_Term_Inactive {
            get {
                return ResourceManager.GetString("Name.Term.Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application finished..
        /// </summary>
        public static string Notification_ApplicationFinished {
            get {
                return ResourceManager.GetString("Notification.ApplicationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting application..
        /// </summary>
        public static string Notification_ApplicationRestarting {
            get {
                return ResourceManager.GetString("Notification.ApplicationRestarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application started..
        /// </summary>
        public static string Notification_ApplicationStarted {
            get {
                return ResourceManager.GetString("Notification.ApplicationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application language has been changed from {fromLanguage} to {toLanguage}..
        /// </summary>
        public static string Notification_LanguageChanged {
            get {
                return ResourceManager.GetString("Notification.LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background screen lock: {Mode}.
        /// </summary>
        public static string Notification_LockScreenDefined {
            get {
                return ResourceManager.GetString("Notification.LockScreenDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {Shortcut} shortcut key has been successfully registered..
        /// </summary>
        public static string Notification_ShortcutDefined {
            get {
                return ResourceManager.GetString("Notification.ShortcutDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {Shortcut} shortcut key cannot be activated..
        /// </summary>
        public static string Notification_ShortcutInvalid {
            get {
                return ResourceManager.GetString("Notification.ShortcutInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shortcut key defined..
        /// </summary>
        public static string Notification_ShortcutRemoved {
            get {
                return ResourceManager.GetString("Notification.ShortcutRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is already in the selected language..
        /// </summary>
        public static string Window_Configuration_LanguageAlreadySelected {
            get {
                return ResourceManager.GetString("Window.Configuration.LanguageAlreadySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the language, the application must be restarted..
        /// </summary>
        public static string Window_Configuration_LanguageChangeConfirm {
            get {
                return ResourceManager.GetString("Window.Configuration.LanguageChangeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the display language.
        /// </summary>
        public static string Window_Configuration_LanguageSelect {
            get {
                return ResourceManager.GetString("Window.Configuration.LanguageSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background screen lock.
        /// </summary>
        public static string Window_Configuration_LockScreen {
            get {
                return ResourceManager.GetString("Window.Configuration.LockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut key for application actions.
        /// </summary>
        public static string Window_Configuration_Shortcut {
            get {
                return ResourceManager.GetString("Window.Configuration.Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Window_Configuration_WindowTitle {
            get {
                return ResourceManager.GetString("Window.Configuration.WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Window_DialogShow_ButtonCancel {
            get {
                return ResourceManager.GetString("Window.DialogShow.ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Window_DialogShow_ButtonClose {
            get {
                return ResourceManager.GetString("Window.DialogShow.ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Window_DialogShow_ButtonConfirm {
            get {
                return ResourceManager.GetString("Window.DialogShow.ButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interval starts after:.
        /// </summary>
        public static string Window_GroupWork_BreakStartsAfterHowManyRounds_Part1 {
            get {
                return ResourceManager.GetString("Window.GroupWork.BreakStartsAfterHowManyRounds_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rounds. Every {minutes} minute(s)..
        /// </summary>
        public static string Window_GroupWork_BreakStartsAfterHowManyRounds_Part2 {
            get {
                return ResourceManager.GetString("Window.GroupWork.BreakStartsAfterHowManyRounds_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the configuration options..
        /// </summary>
        public static string Window_GroupWork_ConfigurationHint {
            get {
                return ResourceManager.GetString("Window.GroupWork.ConfigurationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of each break:.
        /// </summary>
        public static string Window_GroupWork_DurationOfEachBreak_Part1 {
            get {
                return ResourceManager.GetString("Window.GroupWork.DurationOfEachBreak_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s)..
        /// </summary>
        public static string Window_GroupWork_DurationOfEachBreak_Part2 {
            get {
                return ResourceManager.GetString("Window.GroupWork.DurationOfEachBreak_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of each round:.
        /// </summary>
        public static string Window_GroupWork_DurationOfEachRound_Part1 {
            get {
                return ResourceManager.GetString("Window.GroupWork.DurationOfEachRound_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s)..
        /// </summary>
        public static string Window_GroupWork_DurationOfEachRound_Part2 {
            get {
                return ResourceManager.GetString("Window.GroupWork.DurationOfEachRound_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the participant&apos;s name..
        /// </summary>
        public static string Window_GroupWork_ParticipantAdd {
            get {
                return ResourceManager.GetString("Window.GroupWork.ParticipantAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add a participant..
        /// </summary>
        public static string Window_GroupWork_ParticipantAddHint {
            get {
                return ResourceManager.GetString("Window.GroupWork.ParticipantAddHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a participant enter a name..
        /// </summary>
        public static string Window_GroupWork_ParticipantNameEmpty {
            get {
                return ResourceManager.GetString("Window.GroupWork.ParticipantNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant: {Participant}
        ///
        ///To activate or deactivate: right button.
        ///To remove: left button..
        /// </summary>
        public static string Window_GroupWork_ParticipantRemoveHint {
            get {
                return ResourceManager.GetString("Window.GroupWork.ParticipantRemoveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly sort the participants..
        /// </summary>
        public static string Window_GroupWork_ParticipantSortHint {
            get {
                return ResourceManager.GetString("Window.GroupWork.ParticipantSortHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Mob.
        /// </summary>
        public static string Window_GroupWork_Start {
            get {
                return ResourceManager.GetString("Window.GroupWork.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to load a new tip..
        /// </summary>
        public static string Window_GroupWork_TipsHint {
            get {
                return ResourceManager.GetString("Window.GroupWork.TipsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading another tip ....
        /// </summary>
        public static string Window_GroupWork_TipsLoading {
            get {
                return ResourceManager.GetString("Window.GroupWork.TipsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Work as MOB.
        /// </summary>
        public static string Window_GroupWork_WindowTitle {
            get {
                return ResourceManager.GetString("Window.GroupWork.WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize window..
        /// </summary>
        public static string Window_Layout_MinimizeWindow {
            get {
                return ResourceManager.GetString("Window.Layout.MinimizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General application notifications..
        /// </summary>
        public static string Window_Layout_NotificationUser {
            get {
                return ResourceManager.GetString("Window.Layout.NotificationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize window..
        /// </summary>
        public static string Window_Layout_ResizeWindow {
            get {
                return ResourceManager.GetString("Window.Layout.ResizeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close application..
        /// </summary>
        public static string Window_Layout_TerminateApplication {
            get {
                return ResourceManager.GetString("Window.Layout.TerminateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notification..
        /// </summary>
        public static string Window_Notification_NoNotification {
            get {
                return ResourceManager.GetString("Window.Notification.NoNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Window_Notification_WindowTitle {
            get {
                return ResourceManager.GetString("Window.Notification.WindowTitle", resourceCulture);
            }
        }
    }
}
